In [1]:
# Import the modules
import numpy as np
import pandas as pd
from pathlib import Path
from sklearn.metrics import balanced_accuracy_score, confusion_matrix, classification_report

---

## Split the Data into Training and Testing Sets

### Step 1: Read the `lending_data.csv` data from the `Resources` folder into a Pandas DataFrame.

In [2]:
# Read the CSV file from the Resources folder into a Pandas DataFrame
# Set the file path
file_path = Path("lending_data.csv")
# Read the CSV file into a Pandas DataFrame
df = pd.read_csv(file_path)


# Review the DataFrame

# Display the first 5 rows of the DataFrame
print(df.head())

   loan_size  interest_rate  borrower_income  debt_to_income  num_of_accounts  \
0    10700.0          7.672            52800        0.431818                5   
1     8400.0          6.692            43600        0.311927                3   
2     9000.0          6.963            46100        0.349241                3   
3    10700.0          7.664            52700        0.430740                5   
4    10800.0          7.698            53000        0.433962                5   

   derogatory_marks  total_debt  loan_status  
0                 1       22800            0  
1                 0       13600            0  
2                 0       16100            0  
3                 1       22700            0  
4                 1       23000            0  


### Step 2: Create the labels set (`y`)  from the “loan_status” column, and then create the features (`X`) DataFrame from the remaining columns.

In [3]:
# Separate the data into labels and features
# Separate the y variable, the labels
y = df["loan_status"]

# Separate the X variable, the features
X = df.drop(columns=["loan_status"])

In [4]:
# Review the y variable Series
print(y)

0        0
1        0
2        0
3        0
4        0
        ..
77531    1
77532    1
77533    1
77534    1
77535    1
Name: loan_status, Length: 77536, dtype: int64


In [5]:
# Review the X variable DataFrame
# YOUR CODE HERE!
print(X)

       loan_size  interest_rate  borrower_income  debt_to_income  \
0        10700.0          7.672            52800        0.431818   
1         8400.0          6.692            43600        0.311927   
2         9000.0          6.963            46100        0.349241   
3        10700.0          7.664            52700        0.430740   
4        10800.0          7.698            53000        0.433962   
...          ...            ...              ...             ...   
77531    19100.0         11.261            86600        0.653580   
77532    17700.0         10.662            80900        0.629172   
77533    17600.0         10.595            80300        0.626401   
77534    16300.0         10.068            75300        0.601594   
77535    15600.0          9.742            72300        0.585062   

       num_of_accounts  derogatory_marks  total_debt  
0                    5                 1       22800  
1                    3                 0       13600  
2                 

### Step 3: Check the balance of the labels variable (`y`) by using the `value_counts` function.

In [6]:
# Check the balance of our target values
y.value_counts()

0    75036
1     2500
Name: loan_status, dtype: int64

### Step 4: Split the data into training and testing datasets by using `train_test_split`.

In [7]:
# Import the train_test_split module
from sklearn.model_selection import train_test_split

# Split the data using train_test_split
# Assign a random_state of 1 to the function
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=1)


---

## Create a Logistic Regression Model with the Original Data

###  Step 1: Fit a logistic regression model by using the training data (`X_train` and `y_train`).

In [8]:
# Import the LogisticRegression module from SKLearn
from sklearn.linear_model import LogisticRegression

# Instantiate the Logistic Regression model
# Assign a random_state parameter of 1 to the model
model = LogisticRegression(random_state=1)

# Fit the model using training data
model.fit(X_train, y_train)

LogisticRegression(random_state=1)

### Step 2: Save the predictions on the testing data labels by using the testing feature data (`X_test`) and the fitted model.

In [9]:
# Make a prediction using the testing data
y_pred = model.predict(X_test)

### Step 3: Evaluate the model’s performance by doing the following:

* Calculate the accuracy score of the model.

* Generate a confusion matrix.

* Print the classification report.

In [10]:
# Print the balanced_accuracy score of the model
from sklearn.metrics import balanced_accuracy_score

# Calculate the balanced accuracy score
balanced_accuracy = balanced_accuracy_score(y_test, y_pred)
print(f"Balanced Accuracy Score : {balanced_accuracy}")


Balanced Accuracy Score : 0.9520479254722232


In [11]:
# Generate a confusion matrix for the model
from sklearn.metrics import confusion_matrix

# Generate the confusion matrix
matrix = confusion_matrix(y_test, y_pred)
print(f"Confusion Matrix:\n{matrix}")

Confusion Matrix:
[[18663   102]
 [   56   563]]


In [12]:
# Print the classification report for the model
from sklearn.metrics import classification_report

# Print the classification report
report = classification_report(y_test, y_pred)
print(f"Classification Report:\n{report}")

Classification Report:
              precision    recall  f1-score   support

           0       1.00      0.99      1.00     18765
           1       0.85      0.91      0.88       619

    accuracy                           0.99     19384
   macro avg       0.92      0.95      0.94     19384
weighted avg       0.99      0.99      0.99     19384



### Step 4: Answer the following question.

**Question:** How well does the logistic regression model predict both the `0` (healthy loan) and `1` (high-risk loan) labels?

**Answer:** 
Based on the classification report, the logistic regression model has high precision, recall, and F1-score for both the healthy loan class (0) and the high-risk loan class (1). Specifically, the model has:

Precision of 1.00 for the healthy loan class, meaning that all of the loans predicted as healthy are actually healthy.
Precision of 0.85 for the high-risk loan class, meaning that 85% of the loans predicted as high-risk are actually high-risk.
Recall of 0.99 for the healthy loan class, meaning that 99% of the actual healthy loans are correctly predicted as healthy by the model.
Recall of 0.91 for the high-risk loan class, meaning that 91% of the actual high-risk loans are correctly predicted as high-risk by the model.
F1-score of 1.00 for the healthy loan class, which is the harmonic mean of precision and recall.
F1-score of 0.88 for the high-risk loan class, which is the harmonic mean of precision and recall.
Overall, the model performs well in predicting both the healthy loan and high-risk loan labels, with high accuracy, precision, recall, and F1-score for both classes.

---

## Predict a Logistic Regression Model with Resampled Training Data

### Step 1: Use the `RandomOverSampler` module from the imbalanced-learn library to resample the data. Be sure to confirm that the labels have an equal number of data points. 

In [13]:
X_train.shape

(58152, 7)

In [14]:
X_resampled.shape

NameError: name 'X_resampled' is not defined

In [15]:
# Import the RandomOverSampler module form imbalanced-learn
from imblearn.over_sampling import RandomOverSampler
# Instantiate the random oversampler model
# # Assign a random_state parameter of 1 to the model
ros = RandomOverSampler(random_state=1)

# Fit the original training data to the random_oversampler model
X_resampled, y_resampled = ros.fit_resample(X_train, y_train)

In [16]:
# Count the distinct values of the resampled labels data
unique, count = np.unique(y_resampled, return_counts=True)
print(dict(zip(unique, count)))


{0: 56271, 1: 56271}


In [17]:
y_train.value_counts()

0    56271
1     1881
Name: loan_status, dtype: int64

### Step 2: Use the `LogisticRegression` classifier and the resampled data to fit the model and make predictions.

In [18]:
# Instantiate the Logistic Regression model
# Assign a random_state parameter of 1 to the model
model = LogisticRegression(random_state=1)

# Fit the model using the resampled training data
model.fit(X_resampled, y_resampled)

# Make a prediction using the testing data
y_pred = model.predict(X_resampled)

In [19]:
model.

SyntaxError: invalid syntax (1068564517.py, line 1)

In [20]:
model.intercept_

array([-5.10537615e-08])

### Step 3: Evaluate the model’s performance by doing the following:

* Calculate the accuracy score of the model.

* Generate a confusion matrix.

* Print the classification report.

In [21]:
# Print the balanced_accuracy score of the model 
from sklearn.metrics import balanced_accuracy_score
balanced_accuracy_score(y_resampled, y_pred)


0.9947308560359689

In [22]:
from sklearn.metrics import confusion_matrix
# Generate a confusion matrix for the model
cm = confusion_matrix(y_resampled, y_pred)
# Print the confusion matrix
print(cm)


[[55964   307]
 [  286 55985]]


In [23]:
# Print the classification report for the model
from sklearn.metrics import classification_report

# Print the classification report for the model
print(classification_report(y_resampled, y_pred))


              precision    recall  f1-score   support

           0       0.99      0.99      0.99     56271
           1       0.99      0.99      0.99     56271

    accuracy                           0.99    112542
   macro avg       0.99      0.99      0.99    112542
weighted avg       0.99      0.99      0.99    112542



In [24]:
print(classification_report(y_resampled, y_pred).replace('\n\n', 
                                                         '\n=====================================================\n'))
print('=====================================================\n')

              precision    recall  f1-score   support
           0       0.99      0.99      0.99     56271
           1       0.99      0.99      0.99     56271
    accuracy                           0.99    112542
   macro avg       0.99      0.99      0.99    112542
weighted avg       0.99      0.99      0.99    112542




### Step 4: Answer the following question

**Question:** How well does the logistic regression model, fit with oversampled data, predict both the `0` (healthy loan) and `1` (high-risk loan) labels?

**Answer:** The logistic regression model fit with oversampled data predicts both the 0 (healthy loan) and 1 (high-risk loan) labels very well. The precision, recall, and f1-score for both labels are all 0.99, indicating that the model is highly accurate in predicting both classes. Additionally, the balanced accuracy score of 0.99 suggests that the model is performing very well overall.